// <auto-generated />
using System;
using Garage_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2.Migrations
{
    [DbContext(typeof(Garage_2Context))]
    partial class Garage_2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2.Models.Vehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWheels")
                        .HasColumnType("int");

                    b.Property<DateTime>("PartkingStartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegNo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = 4,
                            Make = "Volvo",
                            Model = "V70",
                            NoOfWheels = 4,
                            PartkingStartAt = new DateTime(2022, 7, 8, 15, 5, 15, 42, DateTimeKind.Local).AddTicks(3878),
                            RegNo = "MDK626",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            Color = 2,
                            Make = "tesla",
                            Model = "D3",
                            NoOfWheels = 4,
                            PartkingStartAt = new DateTime(2022, 7, 8, 15, 5, 15, 42, DateTimeKind.Local).AddTicks(3906),
                            RegNo = "TTT234",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            Color = 3,
                            Make = "mercedes",
                            Model = "C-Klass",
                            NoOfWheels = 4,
                            PartkingStartAt = new DateTime(2022, 7, 8, 15, 5, 15, 42, DateTimeKind.Local).AddTicks(3909),
                            RegNo = "ABC123",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 4,
                            Color = 1,
                            Make = "Volvo",
                            Model = "Volvobuss",
                            NoOfWheels = 8,
                            PartkingStartAt = new DateTime(2022, 7, 8, 15, 5, 15, 42, DateTimeKind.Local).AddTicks(3911),
                            RegNo = "DUM666",
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 5,
                            Color = 3,
                            Make = "Princess",
                            Model = "Yatch",
                            NoOfWheels = 0,
                            PartkingStartAt = new DateTime(2022, 7, 8, 15, 5, 15, 42, DateTimeKind.Local).AddTicks(3913),
                            RegNo = "MUU775",
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 6,
                            Color = 0,
                            Make = "Volvo",
                            Model = "V90",
                            NoOfWheels = 4,
                            PartkingStartAt = new DateTime(2022, 7, 8, 15, 5, 15, 42, DateTimeKind.Local).AddTicks(3915),
                            RegNo = "YUU223",
                            VehicleType = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
